ASP_Eindtest/Models/CBUserModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ASP_Eindtest.Models
{
    public class CBUserModel
    {
        [Required(ErrorMessage = "UserName is required")]
        public string Naam { get; set; }
        [Required(ErrorMessage = "Postcode is required")]
        public int Postcode { get; set; }
    }
}

ASP_Eindtest/Models/ErrorViewModel.cs
using System;

namespace ASP_Eindtest.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP_Eindtest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ASP_Eindtest.Models;
using Data.Models;
using Data.Repositories;
using ASP_Eindtest.Services;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;

namespace ASP_Eindtest.Controllers
{
    public class HomeController : Controller
    {
        private KlantService klantService;
        private VideoVerhuurContext VideoVerhuurContext_;
        public HomeController(KlantService klantService, VideoVerhuurContext context)
        {
            this.klantService = klantService;
            VideoVerhuurContext_ = context; 
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(CBUserModel model)
        {
            var klant = VideoVerhuurContext_.Klanten
                                        .Where(k => k.PostCode == model.Postcode)
                                        .FirstOrDefault();
            ViewBag.klant = klant;
            var geserializeerdeklant = JsonConvert.SerializeObject(klant);
            HttpContext.Session.SetString("klant", geserializeerdeklant);
            if (klant != null && klant.Naam == model.Naam.ToUpper())
            {
                return View("Landing", klant);
            }

            return View("Landing", klant);
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

ASP_Eindtest/Controllers/VerhuringenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASP_Eindtest.Services;
using Data.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace ASP_Eindtest.Controllers
{
    public class VerhuringenController : Controller
    {
        private GenreService genreService;
        private VideoVerhuurContext videoVerhuurContext;
        private WinkelmandService winkelmandService;
        private FilmService filmService;
        public VerhuringenController(GenreService genreService,VideoVerhuurContext videoVerhuurContext, WinkelmandService winkelmandService,FilmService filmService )
        {
            this.genreService = genreService;
            this.videoVerhuurContext = videoVerhuurContext;
            this.winkelmandService = winkelmandService;
            this.filmService = filmService;
        }
        public IActionResult Index()
        {
            var klant = HttpContext.Session.GetString("klant");
            if (string.IsNullOrEmpty(klant))
            {
                ViewBag.klant = "geen"; 
 }
            else
            {
                ViewBag.klant =
                JsonConvert.DeserializeObject<Klant>(klant); 
            }
            return View(genreService.GetAllGenres());
        }
        public async Task<IActionResult> Details(int? id)
        {
            var klant = HttpContext.Session.GetString("klant");
            if (string.IsNullOrEmpty(klant))
            {
                ViewBag.klant = "geen";
            }
            else
            {
                ViewBag.klant =
                JsonConvert.DeserializeObject<Klant>(klant);
            }

            if (id == null)
            {
                return NotFound();
            }

            var genre = await videoVerhuurContext.Genres
                .Include(g => g.Films)
                .FirstOrDefaultAsync(m => m.GenreId == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }
        public IActionResult Huren(int id)
        {
            var film = filmService.GetFilmById(id);
            winkelmandService.Add(film);
            return RedirectToAction("Mandje");          
        }
        public IActionResult Verwijderen(int id)
        {
            var film = filmService.GetFilmById(id);
            if (film == null)
            {
                return NotFound();
            }
            return View(film);
        }

        [HttpPost, ActionName("Verwijderen")]
        [ValidateAntiForgeryToken]
        public IActionResult VerwijderenConfirmed(int id)
        {
            winkelmandService.Delete(id);
            return RedirectToAction(nameof(Mandje));
        }
        public IActionResult Mandje()
        {
            return View(winkelmandService.FindAll());
        }

        public IActionResult Afrekenen()
        {
            var klant = HttpContext.Session.GetString("klant");
            if (string.IsNullOrEmpty(klant))
            {
                ViewBag.klant = "geen";
            }
            else
            {
                ViewBag.klant =
                JsonConvert.DeserializeObject<Klant>(klant);
            }
            decimal totaal = 0;
            foreach(var film in winkelmandService.FindAll())
            {
                totaal += film.Prijs;
            }
            ViewBag.totaal =  totaal;
            return View(winkelmandService.FindAll());
        }
    }
}

ASP_Eindtest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model ASP_Eindtest.Models.CBUserModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style type="text/css">
        .bs-example {
            height: 220px;
        }

        .centerlook {
            font-weight: bold;
            width: 1000px;
        }

        .error {
            font-weight: bold;
            width: 1000px;
            color: red;
        }

        .loginbtn {
            padding-left: 100px;
        }
    </style>

</head>
<body>

    @using (Html.BeginForm())
    {
        <div class="form-group centerlook">
            <label>Naam: </label>
            @Html.EditorFor(model => model.Naam)*
            @Html.ValidationMessageFor(model => model.Naam)
        </div>
        <div class="form-group centerlook">
            <label>Postcode:</label>
            @Html.EditorFor(model => model.Postcode) *
            @Html.ValidationMessageFor(model => model.Postcode)

        </div>
        <div class="loginbtn">

            <input type="submit" value="Login" class="btn btn-primary" />

        </div>
    }
 
</body>
</html>

ASP_Eindtest/Views/Home/Landing.cshtml
@model Klant
@{
    ViewData["Title"] = "Landing";
}
@if (Model != null)
{
    <a class="nav-link" asp-area=""
        asp-controller="Verhuringen" asp-action="Index">
        Ga naar verhuringen
    </a>
}
else
{
    <a class="nav-link" asp-area=""
        asp-controller="Home" asp-action="Index">
        Foutieve gegevens, probeer opnieuw
    </a>
}

ASP_Eindtest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP_Eindtest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP_Eindtest</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ASP_Eindtest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ASP_Eindtest/Views/Verhuringen/Afrekenen.cshtml
@model IEnumerable<Film>
@{
    ViewData["Title"] = "Afrekenen";
}

<h1>Afrekenen</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                Titel
            </th>
            <th>
                Prijs
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Titel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prijs)
                </td>>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <th>
                Totaal
            </th>
            <th>
                 @(((decimal)ViewBag.totaal).ToString("C2"))
            </th>
        </tr>
    </tfoot>
</table>

<p>wordt gefactureerd aan:</p>
<p>@ViewBag.klant.Voornaam @ViewBag.klant.Naam</p>
<p></p>
<p>@ViewBag.klant.StraatNr</p>
<p></p>
<p>@ViewBag.klant.PostCode @ViewBag.klant.Gemeente</p>

ASP_Eindtest/Views/Verhuringen/Details.cshtml
@model Genre
@{
    ViewData["Title"] = "Details";
}

<h1>@Model.GenreNaam</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                Titel
            </th>
            <th>
                Prijs
            </th>
            <th>
                In Voorraad
            </th>
            <th>
                Huren
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Films)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Titel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prijs)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InVoorraad)
                </td>
                <td>
                    @if (item.InVoorraad != 0)
                    {
                      <a asp-action="Huren" asp-route-id="@item.FilmId"><img src="~/Images/plus.png" /></a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
<a class="nav-link" asp-area=""
   asp-controller="Verhuringen" asp-action="Index">
    Terug naar genre overzicht
</a>

ASP_Eindtest/Views/Verhuringen/Index.cshtml
@model IEnumerable<Genre>
@{
    ViewData["Title"] = "Index";
}

<h1>Klik op het gewenste GENRE</h1>
<table class="table table-striped">
    <tbody>
        <tr>
            @foreach (var item in Model)
            {
                <td>
                    <a asp-action="Details" asp-route-id="@item.GenreId">@item.GenreNaam</a>
                </td>

            }

        </tr>
    </tbody>
</table>

ASP_Eindtest/Views/Verhuringen/Mandje.cshtml
@model IEnumerable<Film>
@{
    ViewData["Title"] = "Mandje";
}
<h1>Winkelmandje</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                Titel
            </th>
            <th>
                Prijs
            </th>
            <th>
                Verwijderen
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Titel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prijs)
                </td>>
                <td>
                    <a asp-action="verwijderen" asp-route-id="@item.FilmId"><img src="~/Images/delete.png" /></a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a class="nav-link" asp-area=""
   asp-controller="Verhuringen" asp-action="Index">
    Verder winkelen
</a>
<a class="nav-link" asp-area=""
   asp-controller="Verhuringen" asp-action="Afrekenen">
    Afrekenen
</a>

ASP_Eindtest/Views/Verhuringen/Verwijderen.cshtml
@model Film
@{
    ViewData["Title"] = "Verwijderen";
}

<h1>Verwijder gehuurde film</h1>

<p>Ben je zeker dat je "@Model.Titel" niet wil huren?</p>

<form asp-action="Verwijderen">
    <input type="submit" value="Verwijderen" class="btn btn-danger" /> |
    <a class="btn btn-danger" asp-area=""
       asp-controller="Verhuringen" asp-action="Mandje">
        Nee
    </a>
</form>